### ISSUE TITLE
create a template DSL for search forms

### ISSUE THREAD

**Issue by jeremybmerrill** [newsdev/stevedore#2]
There's a lot of boilerplate in the [search_form templates](/templates/search_form). A DSL to "automatically" add that boilerplate (`form-group`, `form-notes`, etc. etc.) to distinguish the interesting content from the boilerplate would be really neat.

YAML might be a good place to start, so a template looks like:

```
fields:
  - title: Full text
    input: <input name="search" id="search" class="form-control" placeholder="Your query..." value="{{= search.query_string.replace(/\"/g, "&quot;") }}" type="text">
    notes: my notes whatever they are
```

Or:

```
fields:
  - title: Full text
    input: text/query_string
    notes: my notes whatever they are
  - title: Subject
    input: text/subject
    notes: my notes whatever they are
  - title: Date sent
    input: daterange/sent
    notes: my notes whatever they are
```

(This idea isn't fully developed, but has a lot of freedom for how to implement it.)
